### ISSUE TITLE
crime.csv file missing

### ISSUE THREAD

**Issue by shubham99bisht** [lakshyaag/CrimeInIndia#1]
Hello, thanks for the amazing repository. Your code helped me a lot in learning how to build R shiny apps.
Can you please share the "crime.csv" file which you used before preprocessing the data or please direct me from where I can download that data file. I would like to explore more and build some more interesting features.

Thanks.

**Comment by lakshyaag** [comment]
I have uploaded the requested file.

**Comment by shubham99bisht** [comment]
Thanks @lakshyaag!
